name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  md-lint:
    name: Lint README.md
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          files: README.md
